### ISSUE TITLE
Support scoped modules

### ISSUE THREAD

**Issue by Mouvedia** [matteofigus/npm-stats-www#11]
Publicly published scoped modules are not supported.
cf npm/download-counts#23

e.g.
http://www.npm-stats.com/string
https://www.npmjs.com/~string

**Comment by Mouvedia** [comment]
@matteofigus https://github.com/npm/download-counts/issues/23#issuecomment-294016319

**Comment by soyuka** [comment]
Was just going to quote that :D 

To spare a useless comment there's the blog article about scoped packages statistics : 

http://blog.npmjs.org/post/159539048360/scope-support-in-search-and-download-stats

> At long last, we provide download statistics for scoped packages like @types/lodash and @angular/common on our website. Hooray! We finally got to close one of our oldest bugs!

Anyway, since the endpoint for the stat doesn't change `https://api.npmjs.org/downloads/range/last-week/@types/express` there shouldn' be much to change here to get that to work! I may work on a patch this wek end (if it doesn't get fixed by then!).

**Comment by Mouvedia** [comment]
@soyuka it's been a long weekend :)

**Comment by soyuka** [comment]
> @soyuka it's been a long weekend :)

Thanks for the reminder :D. Open source software you know :D.

This should be fixed upwards in npm-stats though https://github.com/hughsk/npm-stats/issues/17

**Comment by matteofigus** [comment]
This should now be fixed.
